name: Automated tests workflow_dispatch

on: # если, в какой ситуации
  workflow_dispatch: # запускать в ручном режиме
    inputs:
      deployment_target:
        description: 'Choose target'
        required: true
        default: first_test
        type: choice
        options:
          - first_test
          - second_test

permissions: # права
  contents: write
  pages: write
  id-token: write


#  download-history:
#    runs-on: ubuntu-latest
#
#    name: 'Download history'
#    steps:
#      - name: 'Setup python'
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.12"
#
#      - run: |
#          echo "Set ARTIFACT_ID"
#          ARTIFACT_ID=$(curl -L \
#          -H "Accept: application/vnd.github.v3+json" \
#          -H "X-GitHub-Api-Version: 2022-11-28" \
#          "https://api.github.com/repos/kotov-e/autotest_docker/actions/artifacts?name=allure-results" \
#          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") \
#          && \
#          curl -L \
#          -H "Accept: application/vnd.github.v3+json" \
#          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
#          -H "X-GitHub-Api-Version: 2022-11-28" \
#          "https://api.github.com/repos/kotov-e/autotest_docker/actions/artifacts/$ARTIFACT_ID/zip" -o artifact.zip
#
#      - name: 'Debug - Show downloaded file'
#        run: |
#          echo "Artifact ID: $ARTIFACT_ID"
#          echo "Current directory: $(pwd)"
#          echo "Files: $(ls -la)"
#          echo "File size: $(wc -c < artifact.zip)"
#          echo "File content:"
#          cat artifact.zip
#
#
#      - run:  mkdir allure-results && unzip artifact.zip -d allure-results
#
#      - name: 'Store allure history'
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-results
#          path: allure-results
#          retention-days: 1


jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      first_test: ${{ steps.first_test.outputs }}
      second_test: ${{ steps.second_test.outputs }}

    steps:
      - name: 'Chekout repository'
        uses: actions/checkout@v4 # готовый action
      - name: 'Setup python'
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: 'Install dependencies'
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        #run: sudo apt-get isntall google-chrome-stable
      - name: 'Install playwright chrome'
        run: playwright install --with-deps chromium
      - name: 'Download history'
        uses: actions/download-artifact@v4
      - name: 'first_test'
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest ./test_main.py::test_wiki1 -s -v --alluredir=allure-results
      - name: 'second_test'
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest ./test_main.py::test_wiki2 -s -v --alluredir=allure-results
      - name: 'Save allure results'
        uses: actions/upload-artifact@v4 # v4 (409) Conflict: an artifact with this name already exists on the workflow run
        with:
          name: allure-results
          path: allure-results
          retention-days: 1 # сохранять артефакты не более 1 дня

  generate_report:
    runs-on: ubuntu-latest
    needs: test # запустится только после тестов
    name: 'Generate report'
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.36.0/allure-2.36.0.tgz && sudo tar -zxvf allure-2.36.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.36.0/bin/allure /usr/bin/allure
      - name: 'Download allure results'
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site
      - name: 'Save generated report as artifact'
        uses: actions/upload-artifact@v4 #v4 (409) Conflict: an artifact with this name already exists on the workflow run
        with:
          name: _site
          path: _site
          retention-days: 1 # сохранять артефакты не более 1 дня

  publish-report:
    runs-on: ubuntu-latest
    needs: generate_report
    name: 'Publish report'
    steps:
      - name: 'Download allure results as artifact'
        uses: actions/download-artifact@v4
      - name: 'Upload Pages artifact'
        uses: actions/upload-pages-artifact@v3
      - name: 'Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@v4 #v1.2.9

      - name: 'Print outputs first_test'
        run: |
            echo "Outputs: ${{ steps.first_test.outcome }}"

      # отправка сообщения в группу телеграм # my_chat_id: 1293461593
      #description: 'Send message to telegram if tests passed'
      - name: 'Send message success'
        if: needs.first_test.outputs == 'success'
        run: |
            curl --location 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' --header 'Content-Type: application/json' --data '{ "chat_id": 1293461593, "text": "✅ Test passed. Report is available at https://kotov-e.github.io/autotest_docker/", "parse_mode": "HTML" }'
            curl --location 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' --header 'Content-Type: application/json' --data '{ "chat_id": -1002057224550, "text": "✅ Test passed. Report is available at https://kotov-e.github.io/autotest_docker/", "parse_mode": "HTML" }'
      - name: 'Send message failure'
      #description: 'Send message to telegram if tests failed'
        if: needs.first_test.outputs == 'failure'
        run: |
            curl --location 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' --header 'Content-Type: application/json' --data '{ "chat_id": 1293461593, "text": "❌ Test failed. Report is available at https://kotov-e.github.io/autotest_docker/", "parse_mode": "HTML"  }'
            curl --location 'https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage' --header 'Content-Type: application/json' --data '{ "chat_id": -1002057224550, "text": "❌ Test failed. Report is available at https://kotov-e.github.io/autotest_docker/", "parse_mode": "HTML"  }'