name: Automated tests workflow_dispatch

on: # если, в какой ситуации
  workflow_dispatch: # запускать в ручном режиме
    inputs:
      deployment_target:
        description: 'Choose target'
        required: true
        default: first_test
        type: choice
        options:
          - first_test
          - second_test


permissions: # права
  contents: write
  pages: write
  id-token: write

jobs:
  download-history:
    runs-on: ubuntu-latest

    name: 'Download history'
    steps:
      - name: 'Setup python'
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - run: >
          ARTIFACT_ID=$(curl -L 
          -H "Accept: application/vnd.github.v3+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          "https://api.github.com/repos/kotov-e/autotest_docker/actions/artifacts?name=allure-results" 
          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") 
          &&
          curl -L 
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: Bearer $${{ secrets.TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          "https://api.github.com/repos/kotov-e/autotest_docker/actions/artifacts/$ARTIFACT_ID/zip" -o allure-results.zip

      - name: 'Debug - Show downloaded file'
        run: |
                  echo "Current directory: $(pwd)"
                  echo "Files: $(ls -la)" 
                  echo "File size: $(wc -c < allure-results.zip)"
                  echo "File content: 
                  cat allure-results.zip
                  echo ""
                  

      - run:  mkdir allure-results && unzip allure-results.zip -d allure-results

      - name: 'Store allure history'
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1



  test:
    runs-on: ubuntu-latest
    needs: download-history

    steps:

      - name: 'Chekout repository'
        uses: actions/checkout@v4 # готовый action

      - name: 'Setup python'
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 'Install dependencies'
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        #run: sudo apt-get isntall google-chrome-stable
      - name: 'Install playwright chrome'
        run: playwright install --with-deps chromium

      - name: 'Download history'
        uses: actions/download-artifact@v4

      - name: 'first_test'
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest ./test_main.py::test_wiki1 -s -v --alluredir=allure-results

      - name: 'second_test'
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest ./test_main.py::test_wiki2 -s -v --alluredir=allure-results

      - name: 'Save allure results'
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1 # сохранять артефакты не более 1 дня


  generate_report:
    runs-on: ubuntu-latest
    needs: test # запустится только после тестов
    name: 'Generate report'
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.36.0/allure-2.36.0.tgz && sudo tar -zxvf allure-2.36.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.36.0/bin/allure /usr/bin/allure
      - name: 'Download allure results'
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site
      - name: 'Save generated report as artifact'
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1 # сохранять артефакты не более 1 дня

  publish-report:
    runs-on: ubuntu-latest
    needs: generate_report
    name: 'Publish report'
    steps:
      - name: 'Download allure results as artifact'
        uses: actions/download-artifact@v4
      - name: 'Upload Pages artifact'
        uses: actions/upload-pages-artifact@v3
      - name: 'Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@v4 #v1.2.9
